
services:
  balancer:
    extends:
      file: compose_base.yml
      service: balancer
  local_base:
    extends:
      file: compose_base.yml
      service: worker_base
    volumes:
      # - /homes/80/eltayeb/code:/mount
      - /homes/80/eltayeb/artifacts:/data
      # - /export/:/scratch
      # - /export/fn03/eltayeb/bbc/:/data
      # - /export/fn03/eltayeb/bbc/:/share
    profiles:
        - local_base

  worker0:
    extends:
      service: local_base
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              device_ids: ['0']
    environment:
      - ROUTER_ADDRESS=http://127.0.0.1:${SERVER_PORT}
      - SELF_HOSTNAME=127.0.0.1
      - PORT=8711
      - VLLM_PORT=8712
      - HF_TOKEN=${HF_TOKEN}
      - HF_HOME=/data/.cache/huggingface 

  worker1:
    extends:
      service: local_base
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              device_ids: ['1']
    environment:
      - ROUTER_ADDRESS=http://127.0.0.1:${SERVER_PORT}
      - SELF_HOSTNAME=127.0.0.1
      - PORT=8713
      - VLLM_PORT=8714
      - HF_TOKEN=${HF_TOKEN}
      - HF_HOME=/data/.cache/huggingface

  worker2:
    extends:
      service: local_base
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              device_ids: ['2']
    environment:
      - ROUTER_ADDRESS=http://127.0.0.1:${SERVER_PORT}
      - SELF_HOSTNAME=127.0.0.1
      - PORT=8715
      - VLLM_PORT=8716
      - HF_TOKEN=${HF_TOKEN}
      - HF_HOME=/data/.cache/huggingface


  worker3:
    extends:
      service: local_base
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              device_ids: ['3']
    environment:
      - ROUTER_ADDRESS=http://127.0.0.1:${SERVER_PORT}
      - SELF_HOSTNAME=127.0.0.1
      - PORT=8717
      - VLLM_PORT=8718
      - HF_TOKEN=${HF_TOKEN}
      - HF_HOME=/data/.cache/huggingface


  worker4:
    extends:
      service: local_base
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              device_ids: ['4']
    environment:
      - ROUTER_ADDRESS=http://127.0.0.1:${SERVER_PORT}
      - SELF_HOSTNAME=127.0.0.1
      - PORT=8719
      - VLLM_PORT=8720
      - HF_TOKEN=${HF_TOKEN}
      - HF_HOME=/data/.cache/huggingface

  worker5:
    extends:
      service: local_base
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              device_ids: ['5']
    environment:
      - ROUTER_ADDRESS=http://127.0.0.1:${SERVER_PORT}
      - SELF_HOSTNAME=127.0.0.1
      - PORT=8721
      - VLLM_PORT=8722
      - HF_TOKEN=${HF_TOKEN}
      - HF_HOME=/data/.cache/huggingface

  worker6:
    extends:
      service: local_base
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              device_ids: ['6']
    environment:
      - ROUTER_ADDRESS=http://127.0.0.1:${SERVER_PORT}
      - SELF_HOSTNAME=127.0.0.1
      - PORT=8723
      - VLLM_PORT=8724
      - HF_TOKEN=${HF_TOKEN}
      - HF_HOME=/data/.cache/huggingface

  worker7:
    extends:
      service: local_base
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              device_ids: ['7']
    environment:
      - ROUTER_ADDRESS=http://127.0.0.1:${SERVER_PORT}
      - SELF_HOSTNAME=127.0.0.1
      - PORT=8725
      - VLLM_PORT=8726
      - HF_TOKEN=${HF_TOKEN}
      - HF_HOME=/data/.cache/huggingface