
services:
  balancer:
    extends:
      file: compose_base.yml
      service: balancer

  worker1:
    extends:
      file: compose_base.yml
      service: worker_base
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              device_ids: ['0']
    environment:
      - ROUTER_ADDRESS=http://127.0.0.1:${SERVER_PORT}
      - SELF_HOSTNAME=127.0.0.1
      - PORT=8900
      - HF_TOKEN=${HF_TOKEN}

  worker2:
    extends:
      file: compose_base.yml
      service: worker_base
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              device_ids: ['1']
    environment:
      - ROUTER_ADDRESS=http://127.0.0.1:${SERVER_PORT}
      - SELF_HOSTNAME=127.0.0.1
      - PORT=9900
      - HF_TOKEN=${HF_TOKEN}